# Generated by Django 4.2.7 on 2023-12-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_capital_capitals_rename_country_countrys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capitals',
            new_name='Capital',
        ),
        migrations.RenameModel(
            old_name='Countrys',
            new_name='Country',
        ),
    ]
